import { Inter } from "next/font/google";
import "./globals.css";
import About from "./About/page";
import Link from "next/link";
About;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="list-none justify-evenly w-100 m-10 flex rootHeader w-[500px]">
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/Items">Items</Link>
          </li>
          <li>
            <Link href="/About">Contact Us</Link>
          </li>
        </div>
        {children}
      </body>
    </html>
  );
}
